version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
    depends_on:
      - db
